Repository paritytech/ink, pull requests merged in 2020-03, with the labels that each got.

#343 CI fixes
  .gitlab-ci.yml
  abi/Cargo.toml
  abi/derive/Cargo.toml
  alloc/Cargo.toml
  core/Cargo.toml
  core/derive/Cargo.toml
  lang/Cargo.toml
  lang/macro/Cargo.toml
  prelude/Cargo.toml
  primitives/Cargo.toml
Labels: A-CI, B-enhancement

#349 Reworkaround clippy bug
  .gitlab-ci.yml
Labels: A-CI

#357 add bors to ink repo
  .gitlab-ci.yml
  .travis.yml
  bors.toml
Labels: A-CI, B-enhancement

#363 Initial implementation of high-level hashing infrastructure
  core/Cargo.toml
  core/src/env/api.rs
  core/src/env/backend.rs
  core/src/env/engine/off_chain/hashing.rs
  core/src/env/engine/off_chain/impls.rs
  core/src/env/engine/on_chain/ext.rs
  core/src/env/engine/on_chain/impls.rs
  core/src/env/tests.rs
  core/src/hash/accumulator.rs
  core/src/hash/builder.rs
  core/src/hash/hasher.rs
  core/src/hash/mod.rs
  core/src/lib.rs
Labels: A-ink_core
