Repository paritytech/ink, pull requests merged in 2021-08, with the labels that each got.

#871 Add Fuzz Testing to Bump Allocator
  crates/allocator/Cargo.toml
  crates/allocator/src/bump.rs
  crates/allocator/src/lib.rs
Labels: A-ink_core

#892 Remove `DispatchRetCode`
  crates/lang/codegen/src/generator/dispatch.rs
  crates/lang/src/error.rs
  crates/lang/src/lib.rs
Labels: C-bug

#890 Change CI variables source to Vault
  .gitlab-ci.yml
Labels: A-CI
