Repository paritytech/ink, pull requests merged in 2021-09, with the labels that each got.

#895 CI: fix coverage
  .gitlab-ci.yml
Labels: B-enhancement, E-in-progress, A-CI

#918 CI: thou shall use vault secrets
  .gitlab-ci.yml
Labels: C-bug, A-CI

#919 CI: chown the built docs
  .gitlab-ci.yml
Labels: C-bug, A-CI

#929 Fix script which triggers downstream pipelines
  scripts/.ci/trigger_pipeline.sh
Labels: A-CI
