Repository paritytech/ink, pull requests merged in 2021-07, with the labels that each got.

#800 ERC-1155 Example
  .config/cargo_spellcheck.dic
  .gitlab-ci.yml
  examples/erc1155/.gitignore
  examples/erc1155/Cargo.toml
  examples/erc1155/lib.rs
Labels: A-examples

#836 Implement binary_search for `collections::Vec`
  .config/cargo_spellcheck.dic
  crates/storage/src/collections/vec/mod.rs
  crates/storage/src/collections/vec/tests.rs
Labels: A-ink_lang

#855 Fix `cargo spellcheck` failure in CI
  .config/cargo_spellcheck.dic
  examples/erc1155/lib.rs
Labels: A-CI

#842 Remove `Salt` in code generation during build_create
  crates/lang/codegen/src/generator/cross_calling.rs
  crates/lang/macro/tests/compile_tests.rs
  crates/lang/macro/tests/ui/pass/08-flipper-as-dependency-trait.rs
  crates/lang/macro/tests/ui/pass/09-static-env.rs
  crates/lang/macro/tests/ui/pass/10-derive-for-storage.rs
  crates/lang/macro/tests/ui/pass/11-alias-storage-struct-impl.rs
Labels: C-bug

#857 Temporarily remove `codecov` CI check
  .gitlab-ci.yml
Labels: A-CI

#831 Add Bump Allocator
  crates/allocator/Cargo.toml
  crates/allocator/src/bump.rs
  crates/allocator/src/lib.rs
  crates/env/Cargo.toml
Labels: A-ink_core

#867 Add fuzz tests for `StorageVec::binary_search*`
  .gitlab-ci.yml
  crates/storage/src/collections/vec/fuzz_tests.rs
Labels: A-ink_core

#874 Update `cargo-spellcheck` configuration
  .config/cargo_spellcheck.dic
  .gitlab-ci.yml
  examples/README.md
Labels: A-CI

#878 Flip the `DEBUG_ENABLED` conditional
  crates/env/src/engine/on_chain/ext.rs
Labels: A-ink_core, C-bug

#882 Add example for mocking chain extensions in off-chain tests
  README.md
  crates/env/src/engine/off_chain/test_api.rs
  examples/rand-extension/lib.rs
Labels: A-examples
