Repository paritytech/ink, pull requests merged in 2023-02, with the labels that each got.

#1630 Change CI Runners
  .gitlab-ci.yml
  scripts/ci/pre_cache.sh
Labels: A-CI

#1645 Support custom environment in E2E tests
  CHANGELOG.md
  crates/e2e/macro/src/codegen.rs
  crates/e2e/macro/src/config.rs
  crates/ink/tests/ui/contract/fail/message-returns-non-codec.stderr
  crates/ink/tests/ui/trait_def/fail/message_output_non_codec.stderr
  examples/custom-environment/.gitignore
  examples/custom-environment/Cargo.toml
  examples/custom-environment/README.md
  examples/custom-environment/lib.rs
Labels: A-ink_e2e

#1670 Fixing `ManualKey<0>` to act properly
  CHANGELOG.md
  crates/storage/traits/src/impls/mod.rs
Labels: OpenZeppelin
